version: '3'
services:
  ###############################################################################
  # POSTGRES
  ###############################################################################
  db:
    image: postgres:14.2-alpine
    container_name: nest-postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest-postgres
    ports:
      - "5432:5432"

  ###############################################################################
  # PROJECT - NODE
  ###############################################################################
  nest-postgres:
    image: nest-postgres
    container_name: nest-postgres
    command: "npm start"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      LOG_LEVEL: "debug"
    networks:
      - nest-postgres-network

networks:
  nest-postgres-network:
    driver: bridge
